apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: web
spec:
  selector:
    matchLabels:
      run: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        run: wordpress
    spec:
      containers:
        - name: wordpress
          image: bitnami/wordpress:latest
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: WORDPRESS_DATABASE_HOST
              value: "10.244.2.34"
            - name: WORDPRESS_DATABASE_USER
              value: bn_wordpress
            - name: WORDPRESS_DATABASE_PASSWORD
              value: bitnami
            - name: WORDPRESS_DATABASE_NAME
              value: bitnami_wordpress
          ports:
            - containerPort: 8080
